apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki/sign/default 
    server: http://vault-advatys.vault-advatys.svc.cluster.local:8200
 
    auth:
      kubernetes:
        role: default 
        mountPath: /v1/auth/kubernetes/
        secretRef:
          name: cert-manager-vault-issuer-token 
          key: token
