apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-{{ .Release.Name }}-{{ .Release.Namespace}}
  namespace: argocd 
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc

  project:  {{ .Release.Name }}-{{ .Release.Namespace}}
  syncPolicy:
    automated: {}

  source:
    repoURL: https://github.com/helm/charts.git 
    targetRevision: master
    path: stable/prometheus-blackbox-exporter 
    helm:
      releaseName: blackbox-{{ .Release.Name }}
      values: |
        ---
        nameOverride: {{ .Release.Name }}-{{ .Release.Namespace}}
        runAsUser: ""       
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 5s
              http:
                valid_http_versions: ["HTTP/1.1", "HTTP/2"]
                no_follow_redirects: false
                preferred_ip_protocol: "ip4"
                tls_config:
                  insecure_skip_verify: true
                  
        serviceMonitor:
          ## If true, a ServiceMonitor CRD is created for a prometheus operator
          ## https://github.com/coreos/prometheus-operator
          ##
          enabled: true
        
          # Default values that will be used for all ServiceMonitors created by `targets`
          defaults:
            labels: {}
            interval: 30s
            scrapeTimeout: 30s
            module: http_2xx
        
          targets:
            - name: vault                 # Human readable URL that will appear in Prometheus / AlertManager
              url: https://{{ .Release.Name }}.{{ .Release.Namespace }}.svc:8200/v1/sys/health?standbyok=true  # The URL that blackbox will scrape
              labels: {}                       # List of labels for ServiceMonitor. Overrides value set in `defaults`
              interval: 60s                    # Scraping interval. Overrides value set in `defaults`
              scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
              module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
