{{- if .Values.placeholder.pvc.create }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.placeholder.pvc.name }}
  annotations:
    {{- range $key, $value := .Values.placeholder.pvc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  storageClassName: {{ .Values.placeholder.pvc.storageClass }}
  accessModes:
    - {{ .Values.placeholder.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.placeholder.pvc.storage }}
{{- end -}}
