{
 "title": "Vaults - Advatys",
 "description": " ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "vaultClusterName",
    "query": "label_values(vault_sys_sealed, service)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "content": "<img src=\"https://adinermie.com/wp-content/uploads/2019/08/HashiVault.png\" alt=\"info\" />"
  },
  {
   "title": "Modify by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"create|delete|renew\", service=\"$vaultClusterName\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  {
   "title": "Read by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"read\",service=\"$vaultClusterName\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(vault_sys_sealed{}[15s]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(vault_sys_initialized{}[15s]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_route_count{service=\"$vaultClusterName\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(vault_route{quantile=\"0.99\", service=\"$vaultClusterName\"}) ",
     "legendFormat": "seconds"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pending Tokens",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vault_token_create_count-vault_token_store_count"
    }
   ]
  },
  {
   "title": "Token Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_token_lookup_count{ service=\"$vaultClusterName\"}[1m])",
     "legendFormat": "Lookup"
    }
   ]
  },
  {
   "title": "Token",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vault_token_create_count{service=\"$vaultClusterName\"}",
     "legendFormat": "Create"
    },
    { "expr": "vault_token_store_count", "legendFormat": "Store" }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Audit Log Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vault_audit_log_request_count{ service=\"$vaultClusterName\"} [1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "sum(irate(vault_audit_log_response_count{ service=\"$vaultClusterName\"} [1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "sum(irate(vault_core_handle_request_count{ service=\"$vaultClusterName\" } [1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Auth Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"rollback\",  service=\"$vaultClusterName\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_set_policy_count{ service=\"$vaultClusterName\"} [1m]))",
     "legendFormat": "set"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count{ service=\"$vaultClusterName\"} [1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container!=\"POD\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~ \"$vaultClusterName-[0-9]*\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "CPU Requests %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU  Limits %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota Detailed ",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"vault-operator\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"vault-raft-[0-9]*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"vault-operator\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"vault-raft-[0-9]*\", container != \"\", container != \"POD\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Requests %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod)  * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Limit %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\", container != \"\", container != \"POD\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$vaultClusterName-[0-9]*\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}