apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: initdashboardrole-{{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  - secrets
  verbs:
  - get
  - update
  - create
  - watch
  - list
  - patch

