apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Release.Name }}-vault-operator"
  namespace: {{ .Values.vaultoperator.argocdConfig.namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.vaultoperator.argocdConfig.targetCluster }}
    
    

  project:  {{ .Values.vaultoperator.argocdConfig.project.name }}
  syncPolicy:
    automated: {}

  source:
    repoURL: https://github.com/banzaicloud/bank-vaults.git 
    targetRevision: master
    path: charts/vault-operator/ 
    helm:
      releaseName: "{{ .Release.Name }}-vault-operator"
