apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: proxy-patch
  namespace: resource-locker-operator 
spec:
  serviceAccountRef: 
    name: default
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: Proxy
      name: cluster
    patchTemplate: |
      spec:
        trustedCA:
          name: "cabundle"
    id: proxy-patch 
    patchType: application/merge-patch+json 
