{{ if .Values.operatorGroup.create }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "olm-helper.fullname" . }}
  labels:
    {{- include "olm-helper.labels" . | nindent 4 }}
spec:
{{ toYaml .Values.operatorGroup.spec | indent 2 }}
{{ end }}