apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "olm-helper.fullname" . }}
  labels:
    {{- include "olm-helper.labels" . | nindent 4 }}

spec:
  channel: "{{ .Values.subscription.channel }}"
  name: "{{ .Values.subscription.package }}" 
  source: "{{ .Values.catalog.name }}"  
  sourceNamespace: "{{ .Values.catalog.namespace }}"